In [1]:
import numpy as np
from math import *
import matplotlib.pyplot as plt

In [2]:
x2 = np.array([-10, -10, 1, 21, 0 , 9]).reshape(-1, 1)

Dictionnaire2 = np.array([(1, 1, 2, 5, 0, 0, 3, -2, 1, 2, 2, 2),
                          (0, -1, -1, 1, 0, 0, 5, 0, 2, 2, 7, -1),
                          (1, 1, 1, 5, 1, 2, 2, 1, 1, 1, 1, 5),
                          (1, 5, 2, 2, 5, 0, -4, 5, 1, 5, 0, 0),
                          (0, 2, 2, 1, 1, 0, 0, 0, 0, 4, -1, -2),
                          (-1, 2, 2, 2, -2, -3, -4, 1, 1, 1, 1, 0)]).astype('float32')


x3 = np.array([[ 0.5,  0.1, -0.3,  0.2, -0.1],
                   [ 0.2,  0.3,  0.1, -0.4,  0.2],
                   [-0.1,  0.4, -0.2,  0.3, -0.5],
                   [ 0.3, -0.1,  0.2,  0.4,  0.1],
                   [-0.2,  0.2, -0.5,  0.1,  0.3]])

Dictionnaire3 = np.array([[ 0.3,  0.2,  0.1, -0.2, -0.1, -0.3, -0.2,  0.1,  0.2,  0.3],
                       [ 0.2, -0.2,  0.3, -0.1,  0.1, -0.3, -0.4, -0.1, -0.2,  0.2],
                       [ 0.1, -0.3,  0.2,  0.3, -0.4, -0.1,  0.3, -0.2, -0.1, -0.3],
                       [-0.2,  0.1,  0.4,  0.2, -0.1, -0.2, -0.1, -0.3,  0.3, -0.4],
                       [-0.1, -0.2, -0.1, -0.3,  0.2,  0.3,  0.2, -0.4, -0.2, -0.1]]).astype('float32')


In [3]:
x, N, D, e = x3,10,Dictionnaire3, 0.001

In [4]:
#Initialisation
Index = []
#x = np.matrix(x)
R = x
k = 0


N1, L1 = np.matrix(x).shape
print("x.shape:","N",N1," L",L1)

N2, K1 = np.matrix(D).shape
print("D.shape:","N",N2, " K",K1)

print("alpha.shape"," K",K1," L",L1)




alpha ={}
alpha_index_tmp = [0]*K1

x.shape: N 5  L 5
D.shape: N 5  K 10
alpha.shape  K 10  L 5


In [5]:
while (np.linalg.norm(R) > e and k < N):
        liste_candidats = []
        print("iteration: ", k+1)
        
        for i in range(K1):
            
            print("R, D[:,i]", R, D[:,i])
            value = abs((D[:,i].dot(R)))/np.linalg.norm(D[:,i])
            
            print(value)
            try:
                if isnan(value):
                    value = 0
            except:
                pass
            #print(value)
            
            liste_candidats.append(value)
            
        print("liste_candidats",liste_candidats)
        normes = [np.linalg.norm(vecteur) for vecteur in liste_candidats]
        print(normes)
        m = np.argmax(normes)
        print("m",m)
        Index.append(m)

        try:
            A = np.c_[A, D[:,m].reshape(-1, 1)]

        except: 
            A = np.array(D[:,m]).reshape(-1, 1)

        #print("D[:,m]",D[:,m])
        pinv = np.linalg.pinv(A)

        #At = np.transpose(A)
        #pinv = (np.linalg.inv(At.dot(A))).dot(At)
        
        print("pinv.dot(x)",pinv.dot(x))
        alpha[str(m)]= pinv.dot(x)
        print("alpha[str(m)]",alpha[str(m)])
        print("A",A)
        new_x = (A).dot(alpha[str(m)])

        R = x - new_x
        
        print("m",m)
        print("alpha",alpha)
        k=k+1

iteration:  1
R, D[:,i] [[ 0.5  0.1 -0.3  0.2 -0.1]
 [ 0.2  0.3  0.1 -0.4  0.2]
 [-0.1  0.4 -0.2  0.3 -0.5]
 [ 0.3 -0.1  0.2  0.4  0.1]
 [-0.2  0.2 -0.5  0.1  0.3]] [ 0.3  0.2  0.1 -0.2 -0.1]
[0.32118204 0.29824046 0.18353259 0.18353258 0.20647416]
R, D[:,i] [[ 0.5  0.1 -0.3  0.2 -0.1]
 [ 0.2  0.3  0.1 -0.4  0.2]
 [-0.1  0.4 -0.2  0.3 -0.5]
 [ 0.3 -0.1  0.2  0.4  0.1]
 [-0.2  0.2 -0.5  0.1  0.3]] [ 0.2 -0.2 -0.3  0.1 -0.2]
[0.34112115 0.44772151 0.21320072 0.10660035 0.08528029]
R, D[:,i] [[ 0.5  0.1 -0.3  0.2 -0.1]
 [ 0.2  0.3  0.1 -0.4  0.2]
 [-0.1  0.4 -0.2  0.3 -0.5]
 [ 0.3 -0.1  0.2  0.4  0.1]
 [-0.2  0.2 -0.5  0.1  0.3]] [ 0.1  0.3  0.2  0.4 -0.1]
[0.41309218 0.21552636 0.16164477 0.19756582 0.07184212]
R, D[:,i] [[ 0.5  0.1 -0.3  0.2 -0.1]
 [ 0.2  0.3  0.1 -0.4  0.2]
 [-0.1  0.4 -0.2  0.3 -0.5]
 [ 0.3 -0.1  0.2  0.4  0.1]
 [-0.2  0.2 -0.5  0.1  0.3]] [-0.2 -0.1  0.3  0.2 -0.3]
[0.05773503 0.01924501 0.34641018 0.26943014 0.42339022]
R, D[:,i] [[ 0.5  0.1 -0.3  0.2 -0.1]
 [ 0.2  

In [14]:
print("\n \n")
print("new_x:", new_x)
print("iteration de fin: ", k)
print("erreur de fin:", np.linalg.norm(R))
print("last_index:",last_index)
print("alpha final:",alpha)
print("Index:",Index)
alpha,last_index,Liste_Index,len_index = alpha,str(m),Index,len(alpha)


 

new_x: [[ 0.50000003  0.1        -0.30000001  0.20000002 -0.1       ]
 [ 0.19999998  0.29999999  0.10000003 -0.40000004  0.2       ]
 [-0.09999999  0.40000002 -0.20000002  0.3        -0.50000001]
 [ 0.29999999 -0.09999999  0.19999997  0.40000001  0.1       ]
 [-0.20000001  0.19999999 -0.49999999  0.09999997  0.30000001]]
iteration de fin:  5
erreur de fin: 8.633122179843507e-08
last_index: 3
alpha final: {'4': array([[-2.60869539e-01, -3.91304308e-01,  5.55111512e-17,
        -8.69565129e-01,  1.21739118e+00]]), '8': array([[ 0.01750548, -0.66301964,  0.15317285, -0.67177236,  1.28665198],
       [ 0.9146608 , -0.89277896,  0.50328224,  0.64989058,  0.22757114]]), '6': array([[-0.42326654, -0.82714424, -0.07558332, -0.33946757,  1.2264212 ],
       [ 0.54551427, -1.03023331,  0.31169898,  0.92819587,  0.17712785],
       [-0.83930328, -0.31252051, -0.43558989,  0.63276374, -0.11468946]]), '7': array([[-0.42306066, -0.82672844, -0.07588527, -0.33895448,  1.22681274],
       [ 0.5796

In [7]:
alpha_optimal = alpha[last_index]
print(alpha_optimal)


[[-0.92901244 -1.29012348  1.19135807 -0.66049385  1.30246913]
 [ 0.64300412 -0.90329217  0.10288061  1.053498    0.23251028]
 [-0.83641973 -0.36419753 -0.49382717  0.54320992 -0.21604937]
 [-0.20884769 -0.4218107   0.30658436 -0.52057605 -0.39711934]
 [-0.66049388 -0.60493823  1.65432094 -0.41975311  0.09876542]]


In [8]:
np.matrix(alpha_optimal).shape

(5, 5)

In [9]:
K2, L2 = np.matrix(alpha_optimal).shape
np.matrix(alpha_optimal)
alpha_optimal

array([[-0.92901244, -1.29012348,  1.19135807, -0.66049385,  1.30246913],
       [ 0.64300412, -0.90329217,  0.10288061,  1.053498  ,  0.23251028],
       [-0.83641973, -0.36419753, -0.49382717,  0.54320992, -0.21604937],
       [-0.20884769, -0.4218107 ,  0.30658436, -0.52057605, -0.39711934],
       [-0.66049388, -0.60493823,  1.65432094, -0.41975311,  0.09876542]])

In [10]:
flatten_list = []
if K2 == 1:
    flatten_list = alpha_optimal
else:
    for i in range(K2):
        flatten_list.append(alpha_optimal[i])
        print(alpha_optimal[i])
    
flatten_list
        

[-0.92901244 -1.29012348  1.19135807 -0.66049385  1.30246913]
[ 0.64300412 -0.90329217  0.10288061  1.053498    0.23251028]
[-0.83641973 -0.36419753 -0.49382717  0.54320992 -0.21604937]
[-0.20884769 -0.4218107   0.30658436 -0.52057605 -0.39711934]
[-0.66049388 -0.60493823  1.65432094 -0.41975311  0.09876542]


[array([-0.92901244, -1.29012348,  1.19135807, -0.66049385,  1.30246913]),
 array([ 0.64300412, -0.90329217,  0.10288061,  1.053498  ,  0.23251028]),
 array([-0.83641973, -0.36419753, -0.49382717,  0.54320992, -0.21604937]),
 array([-0.20884769, -0.4218107 ,  0.30658436, -0.52057605, -0.39711934]),
 array([-0.66049388, -0.60493823,  1.65432094, -0.41975311,  0.09876542])]

In [11]:
if K2==1:
    alpha_index_tmp = [0]*K1
else:
    alpha_index_tmp = [[0]*L1]*K1
print(alpha_index_tmp)
print(Liste_Index)
for index,alpha_index in enumerate(Liste_Index):
    alpha_index_tmp[alpha_index] = flatten_list[index]

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[4, 8, 6, 7, 3]


In [12]:
alpha_index_tmp

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 array([-0.66049388, -0.60493823,  1.65432094, -0.41975311,  0.09876542]),
 array([-0.92901244, -1.29012348,  1.19135807, -0.66049385,  1.30246913]),
 [0, 0, 0, 0, 0],
 array([-0.83641973, -0.36419753, -0.49382717,  0.54320992, -0.21604937]),
 array([-0.20884769, -0.4218107 ,  0.30658436, -0.52057605, -0.39711934]),
 array([ 0.64300412, -0.90329217,  0.10288061,  1.053498  ,  0.23251028]),
 [0, 0, 0, 0, 0]]

In [13]:
new_x = D.dot(alpha_index_tmp)
new_x

array([[ 0.50000003,  0.1       , -0.30000001,  0.20000002, -0.1       ],
       [ 0.19999998,  0.29999999,  0.10000003, -0.40000004,  0.2       ],
       [-0.09999999,  0.40000002, -0.20000002,  0.3       , -0.50000001],
       [ 0.29999999, -0.09999999,  0.19999997,  0.40000001,  0.1       ],
       [-0.20000001,  0.19999999, -0.49999999,  0.09999997,  0.30000001]])