In [3]:
import pandas as pd
from math import *
import numpy as np
from scipy.sparse import csr_matrix

In [4]:
alpha = [0,1,0,2,3,4,0,5]
Ti =[]
wi =[]
for i,j in enumerate(alpha):
    if np.linalg.norm(j) != 0:
        Ti.append(i)
        wi.append(j)
        

In [5]:
print(Ti, wi)

[1, 3, 4, 5, 7] [1, 2, 3, 4, 5]


In [6]:
a = np.array([[0,1,1,2,3]])
print(len(a))

1


In [7]:
a.shape

(1, 5)

In [8]:
a = [0,1,2,3,4]
b = [0,0,0,0]
a[:,b]

TypeError: list indices must be integers or slices, not tuple

In [9]:
import numpy as np

# create a random vector of shape (1,5)
vector = np.random.rand(1,5)

# reshape the vector to shape (5,1)
vector = vector.reshape(5,1)

# set up the dictionary
num_atoms = 10
idx_set = np.arange(5)
idxs = np.random.choice(idx_set, num_atoms, replace=True)
print(idxs)
D = vector[:,idxs] / np.linalg.norm(vector[:,idxs])

[4 0 2 2 3 4 3 2 4 4]


IndexError: index 4 is out of bounds for axis 1 with size 1

In [10]:
matrixA = np.matrix([[0,12,4,90],[0,2,4,90]])
np.linalg.matrix_rank(matrixA)

2

In [11]:
import numpy as np 
# Générer une matrice aléatoire
shape = (5, 5)
dense_matrix = np.random.rand(*shape)
print("Matrice dense:")
print(dense_matrix)

# Convertir la matrice en une matrice creuse de manière aléatoire
threshold = 0.9 # seuil pour la sparsité de la matrice
mask = np.random.rand(*shape) < threshold # masque pour la sélection des éléments à conserver
sparse_matrix = csr_matrix(dense_matrix * mask)
print("Matrice creuse:")
print(sparse_matrix.todense())

Matrice dense:
[[7.01304230e-01 3.66102654e-01 5.64716681e-04 3.25064053e-01
  4.37665269e-01]
 [2.22946664e-01 4.00255209e-01 9.15827546e-03 3.29129143e-02
  2.88387691e-01]
 [7.02495928e-01 2.38320350e-01 8.81630964e-01 6.52151291e-01
  7.50161824e-01]
 [1.68995603e-01 2.85137042e-02 5.68945693e-01 3.11712271e-02
  2.50165002e-01]
 [4.01192919e-01 9.51122148e-01 1.11036228e-01 8.84501125e-01
  3.14730342e-01]]
Matrice creuse:
[[7.01304230e-01 3.66102654e-01 5.64716681e-04 3.25064053e-01
  0.00000000e+00]
 [2.22946664e-01 4.00255209e-01 0.00000000e+00 3.29129143e-02
  2.88387691e-01]
 [7.02495928e-01 2.38320350e-01 8.81630964e-01 6.52151291e-01
  7.50161824e-01]
 [1.68995603e-01 2.85137042e-02 5.68945693e-01 3.11712271e-02
  2.50165002e-01]
 [4.01192919e-01 9.51122148e-01 1.11036228e-01 8.84501125e-01
  3.14730342e-01]]


In [12]:
low = 0
high = 1
size =(50,50)
p=0.5
M = 100
threshold = 0.5

In [13]:
a= np.random.uniform(low = low, high = high, size = size)
print(np.linalg.matrix_rank(a), np.linalg.norm(a))
a

50 28.571726233819106


array([[0.65424848, 0.98070556, 0.50681922, ..., 0.35457976, 0.21100125,
        0.08843894],
       [0.93646042, 0.55516956, 0.30643441, ..., 0.08734422, 0.41334978,
        0.74789555],
       [0.34030689, 0.23427636, 0.44834357, ..., 0.99592671, 0.40863785,
        0.71161639],
       ...,
       [0.04586441, 0.61416492, 0.1710644 , ..., 0.39314294, 0.93320943,
        0.01740595],
       [0.00931972, 0.77407299, 0.13466415, ..., 0.98096982, 0.91685519,
        0.89319532],
       [0.7735835 , 0.17027662, 0.87578021, ..., 0.36052847, 0.94833541,
        0.4443931 ]])

In [14]:
b = np.random.choice([-1, 1], size=size, p=[1-p, p])
print(np.linalg.matrix_rank(a), np.linalg.norm(b))
b

50 50.0


array([[ 1, -1,  1, ..., -1,  1, -1],
       [ 1,  1,  1, ..., -1, -1,  1],
       [ 1, -1, -1, ...,  1,  1, -1],
       ...,
       [ 1, -1, -1, ...,  1, -1,  1],
       [-1,  1,  1, ...,  1, -1, -1],
       [-1,  1, -1, ..., -1,  1, -1]])

In [15]:
c = np.random.choice([0, 1], size=size, p=[1-p, p])
print(np.linalg.matrix_rank(c), np.linalg.norm(c))
c

50 35.62302626111375


array([[0, 0, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 1],
       ...,
       [0, 1, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 0, 0]])

In [16]:
d = np.random.normal(0, 1/M, size=size)
print(np.linalg.matrix_rank(d), np.linalg.norm(d))
d

50 0.5048619474581151


array([[-1.65074149e-02, -6.70734398e-03, -1.55542333e-02, ...,
         8.47589762e-03,  1.68585786e-02,  5.80966760e-03],
       [ 2.75062268e-03, -2.39431703e-03,  2.52280441e-04, ...,
        -6.73327229e-04,  1.36833544e-02, -7.99035537e-03],
       [ 6.67220949e-03, -2.79518984e-03,  9.07252189e-03, ...,
        -2.45683994e-03,  4.77909695e-03, -7.75124279e-03],
       ...,
       [-1.63405233e-02, -1.08772277e-02,  6.98744749e-03, ...,
         1.17372909e-02,  8.31265283e-05, -3.68729940e-03],
       [-1.22404686e-02,  4.75008255e-03,  2.50718958e-03, ...,
         1.32123786e-02, -4.81591187e-03, -1.10939166e-02],
       [-1.02597998e-02, -8.95214427e-03, -9.25366838e-03, ...,
        -1.77985732e-02, -1.65161719e-02,  1.47307271e-02]])

In [17]:
dense_matrix = np.random.rand(*size)
print("Matrice dense:")
print(dense_matrix)
print(np.linalg.matrix_rank(dense_matrix), np.linalg.norm(dense_matrix))
# Convertir la matrice en une matrice creuse de manière aléatoire
threshold = 0.5 # seuil pour la sparsité de la matrice
mask = np.random.rand(*size) < threshold # masque pour la sélection des éléments à conserver
sparse_matrix = csr_matrix(dense_matrix * mask)
print("\n\nMatrice creuse:")
e = sparse_matrix.todense()
print(np.linalg.matrix_rank(e), np.linalg.norm(e))
e

Matrice dense:
[[7.27416641e-01 6.91873177e-01 7.56715844e-01 ... 1.87851505e-01
  3.71096798e-01 2.89478744e-01]
 [9.29038569e-01 9.42936618e-01 9.10948818e-01 ... 6.29028451e-01
  7.71026029e-01 2.95195227e-01]
 [1.32083231e-01 7.94339146e-01 9.58931907e-01 ... 1.15075192e-01
  9.51053076e-01 1.67338164e-01]
 ...
 [9.88570647e-01 6.78448534e-04 2.07925713e-01 ... 5.35153535e-01
  3.25966712e-02 5.57444584e-01]
 [8.21268203e-01 4.05284321e-02 9.43600886e-01 ... 4.85855279e-01
  3.49962540e-02 2.37992992e-01]
 [4.38694732e-01 2.13686335e-02 1.66402732e-01 ... 2.65203135e-01
  8.81858790e-01 2.83512353e-01]]
50 28.618095973058647


Matrice creuse:
50 20.226542434162166


matrix([[7.27416641e-01, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 3.71096798e-01, 2.89478744e-01],
        [0.00000000e+00, 0.00000000e+00, 9.10948818e-01, ...,
         0.00000000e+00, 7.71026029e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         0.00000000e+00, 9.51053076e-01, 0.00000000e+00],
        ...,
        [9.88570647e-01, 6.78448534e-04, 0.00000000e+00, ...,
         0.00000000e+00, 3.25966712e-02, 5.57444584e-01],
        [0.00000000e+00, 4.05284321e-02, 0.00000000e+00, ...,
         0.00000000e+00, 3.49962540e-02, 2.37992992e-01],
        [0.00000000e+00, 2.13686335e-02, 0.00000000e+00, ...,
         2.65203135e-01, 0.00000000e+00, 2.83512353e-01]])

In [18]:
import pandas as pd
import numpy as np

M = [25, 30, 45, 50, 100, 150, 200, 250]
df = pd.DataFrame(index=['f1', 'f2', 'f3', 'f4', 'f5'], columns=M)



# Affichage du DataFrame
print(df)

    25   30   45   50   100  150  200  250
f1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
f2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
f3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
f4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
f5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN


In [23]:
import numpy as np #Code A
np.random.seed(0) #Code B
s=np.random.choice(5,10)  #Code C
print(s)# Code D

[4 0 3 3 3 1 3 2 4 0]
